### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by MrAbdelaziz** [EvgenyGusarov/zvezdin-py#1]
Hey,
thanks for this helpful project,

I'm wondering about the results (losses/profits ..) can you share your experince with this project, 
and let me know if you are still working on this project?

Waiting for your feedback

**Comment by big-striped-cat** [comment]
Hi!
The project is in very early stage. Currently I'm not working on project.

**Comment by big-striped-cat** [comment]
@MrAbdelaziz  Why did you select such a title for the topic? If you have found a bug, then more detailed explanation needed.

**Comment by MrAbdelaziz** [comment]
Hey @EvgenyGusarov 
yes, I'm facing a problem with the project,

this is the command I have used :
python app.py backtest --coin LAZIOUSDT --strategy levels-v1 --from 2022-08-23 --to 2022-08-23

market-data for the test : 
[LAZIOUSDT-5m-2022-08-23.csv](https://github.com/EvgenyGusarov/zvezdin-py/files/9483473/LAZIOUSDT-5m-2022-08-23.csv)

as you can see, I added "--coin" to enable multiple cryptos in the project 

the problem I found is sometimes calc_local_maximums return empty arrays for maximums 
also, calc_local_minimums has the same problem 

indices_max, maximums = calc_local_maximums(ma_list)


thanks for your reply 👍

**Comment by big-striped-cat** [comment]
![Screenshot from 2022-09-05 17-49-04](https://user-images.githubusercontent.com/2638197/188481809-cdb98277-7a00-412e-aa08-f2a8c0b831c3.png)


That's the interval causing problems. As you see, no local maximums there. Endpoints do not count. 

It means window size is too small. I think it should be configurable.
https://github.com/EvgenyGusarov/zvezdin-py/blob/main/backtest.py#L17

**Comment by MrAbdelaziz** [comment]
👍  thanks for the answer,
I will try to adjust t parameter!
